name: DataMiner CICD NuGet Solution

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:
  CICD:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@DotNet
    with:
      sonarCloudProjectName: SkylineCommunications_Skyline.DataMiner.CICD.Common
    secrets:
      nugetApiKey: ${{ secrets.NUGETAPIKEY }}
